name: Release

on:
  push:
    tags:
      - v*

jobs:
  release-win:
    name: Release for Windows
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build app
        run: yarn build:win

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: |
            dist/DakokuApp Setup *.exe

  release-mac:
    name: Release for Mac OS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build app
        run: yarn build:mac

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: |
            dist/DakokuApp-*.dmg
            dist/DakokuApp-*-mac.zip
